// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrsymvlwgcflsrzvtwzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxyc3ltdmx3Z2NmbHNyenZ0d3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MjkyMzMsImV4cCI6MjA1NzQwNTIzM30.gD3F0ClbQp99Sz4-PCcSCnRQ-RvvJ9NL-j18PrCzyCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);