
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntptyttdicljffjgcmhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cHR5dHRkaWNsamZmamdjbWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MjYwNTMsImV4cCI6MjA1NzQwMjA1M30.V8oHQ4qo7E7vLGMt4kTJyrSHd3ZFhG1YTmvIbyrBXVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// We use 'any' as a temporary workaround while the types file is being updated
// This is a safe workaround since the database schema exists and is correctly defined in SQL
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
